### PR TITLE
Implement review feature

### LINKED ISSUE #34: Allow players to review their answers and correct answers
So they can improve on interval identification. Ideas:
- display their answers v.s. correct answers - maybe provide button to replay the tones again
- display the top intervals they get wrong (requires data collection over time)
- display bar graph of their stats (visual data representation)

### PR DESCRIPTION
**Pull request by eyeri91**
Towards #34  

 In this PR, I added lines of code that create a game-results object to be saved in `localStorgage`. This object includes the game `score` and an array of `questionsToReview`. 

Every time the `compareAnswers()` runs in `game.js` and a user answer is wrong, a new object with `questionNumber`, `correctAnswer`, `userAnswer`, `note1` and `note2` will be saved in the `questionsToReivew` array.

And when the game is over, `this.#score` of the game and `questionsToReview` array will be saved in the `quizResultsObject`, which eventually will be stored in `this.#scores` in `localStorage`.

### CODE REVIEW

**Comment by kuosandys** [comment]
Tested and works great! Just two points:
- Could we use "Towards <GITHUB_ISSUE>" instead of "Closes <GITHUB_ISSUE>" in the PR description above? While we've implemented the logic part of a review feature, we don't have a UI for it yet. This way we won't lose track of the remaining work to do 🙂 
- Small nitpick on naming - since we're not just storing scores anymore but rather quiz results, what do you think about renaming `#scores` and the `#storeScores`method? Since they're private fields/methods, the impact of the changes should be limited to just our `Game ` class, and it would make the code easier to understand

**Comment by eyeri91** [comment]
> Tested and works great! Just two points:
> 
> * Could we use "Towards <GITHUB_ISSUE>" instead of "Closes <GITHUB_ISSUE>" in the PR description above? While we've implemented the logic part of a review feature, we don't have a UI for it yet. This way we won't lose track of the remaining work to do 🙂

Oh, I didn't know there is "Towards ...". I thought "Closes ..." is sort of all time convention 😅 . Thank you so much!

> * Small nitpick on naming - since we're not just storing scores anymore but rather quiz results, what do you think about renaming `#scores` and the `#storeScores`method? Since they're private fields/methods, the impact of the changes should be limited to just our `Game ` class, and it would make the code easier to understand

That is a very good point. I was thinking maybe `#scores` can be changed to  `#savedQuizResultsData` and `#storeScores` can be called  `#storeQuizResultsData(or Objects)` 

Let me know your opinion over this! 😄

**Comment by kuosandys** [comment]
> That is a very good point. I was thinking maybe #scores can be changed to #savedQuizResultsData and #storeScores can be called #storeQuizResultsData(or Objects)

I like `#storeQuizResultsData`! Or even just `#storeQuizResults` would work too 🙂 I think for the data maybe we should be careful about the "saved" word, since it might be a little unclear where it's currently being "saved". What do you think about just `#quizResultsData`, similar to the method name without the verb?

**Comment by eyeri91** [comment]
OMG I just realized your last comment and I am supposed to update this PR.... 😭  I am so sorry Sandy that I have been leaving this matter until 2023. I can't believe this. 
I will update those names and request the review again!

**Comment by kuosandys** [comment]
> OMG I just realized your last comment and I am supposed to update this PR.... 😭 I am so sorry Sandy that I have been leaving this matter until 2023. I can't believe this. I will update those names and request the review again!
> 
> Btw I agree with your idea to change the `#scores` to `#quizResults`. It makes more sense and gives more consistency

Hey, don't be sorry at all! Also, what I say during code reviews should be viewed as suggestions - if you have a different opinion or think my suggestions are out of place for the PR, please speak up. I try to give feedback rather than just thumbs-up everything, but there's always the danger that I'm being too nit-picky 😅 

I have all the confidence that you can figure out the merging, but please let me know if I can help with anything ❤️

**Review by kuosandys — APPROVED** [review]
LGTM 🚀

**Pull request merged**
